### ISSUE TITLE
Calulcate_score method in controller needs to be moved to a Model

### ISSUE THREAD

**Issue by vemuriPradyumna** [J-Sumer/expertiza#6]
calculate_score methods in controller will be moved to a helper file since there is no explicit model file in the project.

**Comment by vemuriPradyumna** [comment]
Since the original calculate_scores was large, @J-Sumer has split the method into 3 different ones to handle single/ true or false questions and multiple answer questions separately.

**Comment by vemuriPradyumna** [comment]
Comments for these methods were updated.

**Comment by J-Sumer** [comment]
Since calculate_score, multiple_answer_evaluation and single_answer_evaluation methods are helper functions, they are moved to student_quizzes_helper.rb file.
